---
# - name: Update system
#   pacman:
#     update_cache: yes
#     upgrade: yes

- name: Install official packages
  pacman:
    name: "{{ official_packages }}"
    state: present

- name: Install AUR packages via helper script
  ansible.builtin.script: install-aur.sh {{ aur_packages | join(' ') }}
  become: false
