---
# - name: Update system
#   pacman:
#     update_cache: yes
#     upgrade: yes

# - name: Install official packages
#   pacman:
#     name: "{{ official_packages }}"
#     state: present
- name: Install packages with comprehensive error handling
  block:
    - name: Install package batch
      pacman:
        name: "{{ official_packages }}"
        state: present
      register: pkg_install
      
    - name: Display installation result
      debug:
        var: pkg_install.changed
      
  rescue:
    - name: Install packages individually on batch failure
      pacman:
        name: "{{ item }}"
        state: present
      loop: "{{ official_packages }}"
      ignore_errors: yes
      register: individual_installs
      
    - name: Show failed packages
      debug:
        msg: "Failed to install: {{ item.item }}"
      loop: "{{ individual_installs.results }}"
      when: item.failed

- name: Install AUR packages via helper script
  ansible.builtin.script: install-aur.sh {{ aur_packages | join(' ') }}
  become: false
