---
# - name: Update system
#   pacman:
#     update_cache: yes
#     upgrade: yes

- name: Install base packages
  pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ base_packages }}"

- name: Create user
  user:
    name: "{{ username }}"
    groups: wheel
    shell: /bin/zsh


