---
- name: Update package cache
  # ansible.builtin.pacman:
  community.general.pacman:
    state: latest
    update_cache: yes
  become: yes
  tags: base

- name: Install Base packages
  pacman:
    name: "{{ base_packages }}"
    state: present
  become: yes
  tags: base

- name: Configure touchpad for laptops
  ansible.builtin.include_tasks: touchpad.yaml
  when: inventory_hostname in groups['laptops']
  tags: touchpad


# - name: Install additional packages
#   pacman:
#     name: "{{ additional_packages }}"
#     state: present
#   become: yes
#   when: additional_packages is defined
#   tag: base
