[font]
normal = { family = "Cascadia Code NF", style = "Regular" }
size = 10.0

[terminal]
shell.program = "tmux"
shell.args = ["new-session"]

[mouse]
    bindings = [
        { mouse = "Right", action = "Copy" },
    ]

[scrolling]
history = 2000
multiplier = 3

[keyboard]
[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

